name: irods-demo

services:
    irods-catalog:
        build:
            context: irods_catalog
        # 5432 is exposed by default and can conflict with other postgres containers.
        # When the metalnx-db service is no longer needed, this stanza can be removed.
        ports:
            - "5430:5432"
        environment:
            - POSTGRES_PASSWORD=testpassword

    irods-catalog-provider:
        build:
            context: irods_catalog_provider
        shm_size: 500mb
        volumes:
            - ./migration.py:/etc/irods/core.py
            - ./migration_setup_tempZone.sh:/migration_setup_tempZone.sh
        healthcheck:
            test: ["CMD", "su", "-", "irods", "-c", "./irodsctl status | grep Process"]
            interval: 10s
            timeout: 10s
            retries: 3
            start_period: 20s
            start_interval: 10s
        depends_on:
            - irods-catalog

    other-catalog:
        build:
            context: other_catalog
        # 5432 is exposed by default and can conflict with other postgres containers.
        # When the metalnx-db service is no longer needed, this stanza can be removed.
        ports:
            - "5431:5432"
        environment:
            - POSTGRES_PASSWORD=testpassword

    other-catalog-provider:
        build:
            context: other_catalog_provider
        shm_size: 500mb
        volumes:
            - ./migration_setup_otherZone.sh:/migration_setup_otherZone.sh
        healthcheck:
            test: ["CMD", "su", "-", "irods", "-c", "./irodsctl status | grep Process"]
            interval: 10s
            timeout: 10s
            retries: 3
            start_period: 20s
            start_interval: 10s
        depends_on:
            - other-catalog
