name: irods-demo

services:
    irods-catalog:
        build:
            context: irods_catalog
        # 5432 is exposed by default and can conflict with other postgres containers.
        # When the metalnx-db service is no longer needed, this stanza can be removed.
        ports:
            - "5430:5432"
        environment:
            - POSTGRES_PASSWORD=testpassword
        restart: always

    haproxy:
        image: haproxy:latest
        ports:
            - 2247:1247
        volumes:
            - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
        restart: always

    irods-catalog-provider:
        build:
            context: irods_catalog_provider
        shm_size: 500mb
        healthcheck:
            test: ["CMD", "su", "-", "irods", "-c", 'echo -e "\x00\x00\x00\x33<MsgHeader_PI><type>HEARTBEAT</type></MsgHeader_PI>" | (exec 3<>/dev/tcp/127.0.0.1/1247; cat >&3; cat <&3; exec 3<&-)']
            interval: 10s
            timeout: 10s
            retries: 3
            start_period: 20s
            start_interval: 10s
        volumes:
          - demoResc-data:/shared
        restart: always
        depends_on:
            - irods-catalog
            - minio

    irods-catalog-provider2:
        build:
            context: irods_catalog_provider2
        shm_size: 500mb
        healthcheck:
            test: ["CMD", "su", "-", "irods", "-c", 'echo -e "\x00\x00\x00\x33<MsgHeader_PI><type>HEARTBEAT</type></MsgHeader_PI>" | (exec 3<>/dev/tcp/127.0.0.1/1247; cat >&3; cat <&3; exec 3<&-)']
            interval: 10s
            timeout: 10s
            retries: 3
            start_period: 20s
            start_interval: 10s
        volumes:
            - demoResc-data:/shared
        restart: always
        depends_on:
            - irods-catalog
            - irods-catalog-provider
            - minio

    irods-catalog-provider3:
        build:
            context: irods_catalog_provider3
        shm_size: 500mb
        healthcheck:
            test: ["CMD", "su", "-", "irods", "-c", 'echo -e "\x00\x00\x00\x33<MsgHeader_PI><type>HEARTBEAT</type></MsgHeader_PI>" | (exec 3<>/dev/tcp/127.0.0.1/1247; cat >&3; cat <&3; exec 3<&-)']
            interval: 10s
            timeout: 10s
            retries: 3
            start_period: 20s
            start_interval: 10s
        volumes:
            - demoResc-data:/shared
        restart: always
        depends_on:
            - irods-catalog
            - irods-catalog-provider
            - minio

    irods-client-icommands:
        build:
            context: irods_client_icommands
        depends_on:
            irods-catalog-provider:
                condition: service_healthy

    minio:
        image: minio/minio:RELEASE.2024-09-13T20-26-02Z
        ports:
            - "19000:19000"
            - "19001:19001"
        volumes:
            - ./minio-data:/data
        command: minio server /data
        environment: 
          MINIO_ROOT_USER: irods
          MINIO_ROOT_PASSWORD: irodsadmin
          MINIO_ADDRESS: ":19000"
          MINIO_CONSOLE_ADDRESS: ":19001"

volumes:
  demoResc-data:
